---
abstract: 'list changes for CPAN modules'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.0, Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cpan-listchanges
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Algorithm::Diff: 0
  CPAN::DistnameInfo: 0
  LWP: 0
  Module::Metadata: 0
  Pod::Usage: 0
  Try::Tiny: 0
  YAML: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/miyagawa/cpan-listchanges/issues
  homepage: https://github.com/miyagawa/cpan-listchanges
  repository: https://github.com/miyagawa/cpan-listchanges.git
version: 0.06
